(function(){'use strict';
var A=window.SoilRepoAdmin=window.SoilRepoAdmin||{};
A.owner='1337816143';A.repo='soil-type-mapping-inventory';A.branch='main';A.referenceRoot='reference-files/third-soil-survey';A.indexPath='data/admin-import-index.json';A.rawBase='https://raw.githubusercontent.com/'+A.owner+'/'+A.repo+'/'+A.branch+'/';A.tree=null;A.dirs=[];
A.esc=function(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')};
A.clean=function(p){var out=[];String(p||'').replace(/\\/g,'/').split('/').forEach(function(x){x=x.trim();if(!x||x==='.')return;if(x==='..')throw Error('目录中不能包含“..”');out.push(x.replace(/[\u0000-\u001f:*?"<>|]/g,'_'))});return out.join('/')};
A.base=function(p){p=String(p||'');return p.slice(p.lastIndexOf('/')+1)};A.dir=function(p){p=String(p||'');var i=p.lastIndexOf('/');return i<0?'':p.slice(0,i)};
A.raw=function(p){return A.rawBase+String(p||'').split('/').map(encodeURIComponent).join('/')};
A.size=function(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(n>=10485760?1:2)+' MB'};
A.req=function(path,opt){opt=opt||{};var h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(window.SOIL_GITHUB_UPLOAD_TOKEN)h.Authorization='Bearer '+window.SOIL_GITHUB_UPLOAD_TOKEN;if(opt.body)h['Content-Type']='application/json';opt.headers=Object.assign(h,opt.headers||{});return fetch('https://api.github.com/repos/'+A.owner+'/'+A.repo+path,opt).then(function(r){return r.text().then(function(t){var d=t?JSON.parse(t):{};if(!r.ok){var e=Error(d.message||('GitHub API '+r.status));e.status=r.status;throw e}return d})})};
A.loadTree=function(force){if(A.tree&&!force)return Promise.resolve(A.tree);return A.req('/git/trees/'+encodeURIComponent(A.branch)+'?recursive=1').then(function(d){A.tree=d.tree||[];var m={};A.tree.forEach(function(x){var s=(x.path||'').split('/');if(x.type==='tree')m[x.path]=1;for(var i=1;i<s.length;i++)m[s.slice(0,i).join('/')]=1});A.dirs=Object.keys(m).sort(function(a,b){return a.localeCompare(b,'zh-CN')});return A.tree})};
function css(){if(document.getElementById('ref-style'))return;var s=document.createElement('style');s.id='ref-style';s.textContent='.ref-wrap{display:flex;flex-direction:column;gap:13px}.ref-tools{display:flex;gap:9px;flex-wrap:wrap;align-items:center;padding:12px;background:var(--bg2);border:1px solid var(--rule);border-radius:10px}.ref-search{flex:1 1 330px;min-width:220px;padding:8px 11px;border:1px solid var(--rule);border-radius:7px;font:inherit}.ref-btn{display:inline-flex;align-items:center;justify-content:center;padding:6px 11px;border-radius:6px;border:1px solid var(--accent);background:var(--accent);color:#fff;font-size:.78rem;font-weight:600;cursor:pointer;text-decoration:none;white-space:nowrap}.ref-btn.alt{background:#fff;color:var(--accent)}.ref-note{flex:1 1 100%;font-size:.76rem;color:var(--muted)}.ref-cat{border:1px solid var(--rule);border-radius:9px;overflow:hidden;background:#fff}.ref-cat summary{display:flex;gap:10px;align-items:center;padding:11px 14px;background:var(--bg2);font-weight:700;cursor:pointer;list-style:none}.ref-cat summary::-webkit-details-marker{display:none}.ref-count{margin-left:auto;padding:2px 8px;border-radius:99px;background:#dbeafe;color:var(--accent);font-size:.71rem}.ref-file{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px 14px;border-top:1px solid var(--rule)}.ref-name{font-size:.83rem;font-weight:600;overflow-wrap:anywhere}.ref-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:2px;color:var(--muted);font-size:.7rem}.ref-empty{padding:18px;text-align:center;color:var(--muted);font-size:.82rem}@media(max-width:760px){.ref-file{grid-template-columns:1fr}.ref-btn{flex:1 1 auto}}';document.head.appendChild(s)}
function installTab(){var tabs=document.querySelector('header .tabs'),box=document.querySelector('body>.container');if(!tabs||!box)return;var tab=tabs.querySelector('[data-tab="references"]');if(!tab){tab=document.createElement('div');tab.className='tab';tab.dataset.tab='references';tab.textContent='参考文件';tabs.appendChild(tab)}var panel=document.getElementById('tab-references');if(!panel){panel=document.createElement('div');panel.id='tab-references';panel.className='tab-content';panel.innerHTML='<div class="content" id="ref-root"><div class="ref-empty">正在读取参考资料目录……</div></div>';box.appendChild(panel)}if(!tab.dataset.bound){tab.dataset.bound='1';tab.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();document.querySelectorAll('.tab,.tab-content').forEach(function(x){x.classList.remove('active')});tab.classList.add('active');panel.classList.add('active');render(false)})}}
function category(path){var r=path.slice(A.referenceRoot.length+1),s=r.split('/');if(s[0]==='三普成果编制及质量控制主要参考资料')s.shift();return s.length>1?s[0]:'其他资料'}
function rel(path){var r=path.slice(A.referenceRoot.length+1),p='三普成果编制及质量控制主要参考资料/';return r.indexOf(p)===0?r.slice(p.length):r}
function render(force){var root=document.getElementById('ref-root');if(!root)return;root.innerHTML='<div class="ref-empty">正在读取参考资料目录……</div>';A.loadTree(force).then(function(tree){var g={};tree.filter(function(x){return x.type==='blob'&&x.path.indexOf(A.referenceRoot+'/')===0&&!/(^|\/)(README\.md|manifest\.json|archive\.json)$/i.test(x.path)&&!/(^|\/)~\$/.test(x.path)}).forEach(function(x){var c=category(x.path);(g[c]||(g[c]=[])).push(x)});var cs=Object.keys(g).sort(function(a,b){return a.localeCompare(b,'zh-CN')}),count=0;cs.forEach(function(c){count+=g[c].length});var h='<div class="ref-wrap"><div class="ref-tools"><input id="ref-search" class="ref-search" type="search" placeholder="搜索文件名、目录或成果类别"><button id="ref-admin" class="ref-btn">管理员导入</button><button id="ref-refresh" class="ref-btn alt">刷新目录</button><div class="ref-note">仓库内共 '+count+' 个参考文件，保持原目录层级，点击可直接下载。</div></div>';if(!cs.length)h+='<div class="ref-empty">专用目录中暂无实际资料，请使用“管理员导入”。</div>';cs.forEach(function(c,i){g[c].sort(function(a,b){return a.path.localeCompare(b.path,'zh-CN')});h+='<details class="ref-cat" '+(i<3?'open':'')+'><summary><span>'+A.esc(c)+'</span><span class="ref-count">'+g[c].length+' 个文件</span></summary>';g[c].forEach(function(f){var n=A.base(f.path),r=rel(f.path),q=(c+' '+n+' '+r).toLowerCase();h+='<div class="ref-file" data-q="'+A.esc(q)+'"><div><div class="ref-name">'+A.esc(n)+'</div><div class="ref-meta"><span>'+A.esc((n.split('.').pop()||'FILE').toUpperCase())+'</span><span>'+A.size(f.size)+'</span><span>'+A.esc(r)+'</span></div></div><a class="ref-btn alt" target="_blank" rel="noopener" href="'+A.esc(A.raw(f.path))+'">下载</a></div>'});h+='</details>'});h+='</div>';root.innerHTML=h;document.getElementById('ref-search').addEventListener('input',function(){var q=this.value.trim().toLowerCase();root.querySelectorAll('.ref-file').forEach(function(x){x.style.display=!q||x.dataset.q.indexOf(q)>=0?'':'none'});root.querySelectorAll('.ref-cat').forEach(function(x){var v=Array.prototype.some.call(x.querySelectorAll('.ref-file'),function(y){return y.style.display!=='none'});x.style.display=v?'':'none';if(q&&v)x.open=true})});document.getElementById('ref-refresh').onclick=function(){render(true)};document.getElementById('ref-admin').onclick=function(){window.openSoilAdminImport({kind:'reference',suggestedDirectory:A.referenceRoot})}}).catch(function(e){root.innerHTML='<div class="ref-empty">目录加载失败：'+A.esc(e.message)+'</div>'})}
function load(src){return new Promise(function(ok,no){var s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function init(){css();installTab();load('./admin-import.js').catch(function(){console.error('管理员导入脚本加载失败')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();