import test from 'node:test';
import assert from 'node:assert/strict';
import {Service,sha} from '../src/service.mjs';
import {ManagedUploadClient} from '../src/client.mjs';
import {assignment,descriptors,manifest,deletePath,CHUNK,REPO,QUALITY_ROOT,REFERENCE_ROOT,INDEX_PATH,TYPES} from '../src/policy.mjs';
import DIRECTORY from '../src/directory.mjs';
import fs from 'node:fs';
const enc=new TextEncoder(),dec=new TextDecoder();
const ORIGIN='https://1337816143.github.io',ENDPOINT='https://backend.test';
class Storage{map=new Map();async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}async delete(keys){for(const k of Array.isArray(keys)?keys:[keys])this.map.delete(k);}async setAlarm(){} }
class Repository{
  constructor(){this.blobs=new Map();this.trees=new Map();this.commits=new Map();this.refs=new Map();this.calls=[];this.failure=null;this.lostAck=false;}
  async id(value){return (await sha(JSON.stringify(value))).slice(0,40);}
  async init(){const indexSha=await this.addBlob(enc.encode('[]'));const tree=await this.addTree({[INDEX_PATH]:indexSha});this.head=await this.addCommit(tree,[],'baseline');this.refs.set('main',this.head);return this;}
  async addBlob(b){const id=(await sha(b)).slice(0,40);this.blobs.set(id,new Uint8Array(b));return id;}
  async addTree(rows){const id=await this.id(rows);this.trees.set(id,structuredClone(rows));return id;}
  async addCommit(tree,parents,message){const value={tree:{sha:tree},parents,message};const id=await this.id(value);this.commits.set(id,value);return id;}
  async seed(files,index){const base=this.commits.get(this.refs.get('main'));const tree={...this.trees.get(base.tree.sha)};for(const [p,b] of Object.entries(files))tree[p]=await this.addBlob(b);if(index)tree[INDEX_PATH]=await this.addBlob(enc.encode(JSON.stringify(index)));const head=await this.addCommit(await this.addTree(tree),[this.refs.get('main')],'external update');this.refs.set('main',head);return head;}
  ancestor(a,b){if(a===b)return true;return (this.commits.get(b)?.parents||[]).some(p=>this.ancestor(a,p));}
  async fetch(url,options){
    assert.ok(url.startsWith('https://api.github.com/repos/'+REPO+'/'));
    assert.equal(options.headers.Authorization,'Bearer fixture-server-token');
    const u=new URL(url),p=u.pathname.split(REPO)[1],b=options.body?JSON.parse(options.body):null,m=options.method;
    this.calls.push({p,m});
    if(this.failure){const f=this.failure;this.failure=null;if(f.throw)throw f.throw;return Response.json({message:'sensitive upstream detail must not leak'},{status:f.status,headers:f.headers});}
    const response=(x,status=200)=>Response.json(x,{status});
    if(p.startsWith('/git/ref/heads/')){const branch=p.slice(15),head=this.refs.get(branch);return head?response({object:{sha:head}}):response({},404);}
    if(p==='/git/blobs'&&m==='POST'){const bytes=b.encoding==='base64'?Uint8Array.from(atob(b.content),c=>c.charCodeAt(0)):enc.encode(b.content);return response({sha:await this.addBlob(bytes)},201);}
    if(p.startsWith('/git/commits/')&&m==='GET')return response(this.commits.get(p.split('/').at(-1)));
    if(p==='/git/commits'&&m==='POST')return response({sha:await this.addCommit(b.tree,b.parents,b.message)},201);
    if(p==='/git/trees'&&m==='POST'){const rows={...this.trees.get(b.base_tree)};for(const item of b.tree){if(item.sha===null)delete rows[item.path];else rows[item.path]=item.sha||await this.addBlob(enc.encode(item.content));}return response({sha:await this.addTree(rows)},201);}
    if(p.startsWith('/git/trees/')&&m==='GET'){const rows=this.trees.get(p.split('/').at(-1));return response({truncated:false,tree:Object.entries(rows).map(([path,sha])=>({path,sha,type:'blob',mode:'100644'}))});}
    if(p==='/git/refs'&&m==='POST'){const branch=b.ref.replace('refs/heads/','');if(this.refs.has(branch))return response({},422);this.refs.set(branch,b.sha);if(this.lostAck){this.lostAck=false;throw new TypeError('network after reference committed');}return response({object:{sha:b.sha}},201);}
    if(p==='/git/refs/heads/main'&&m==='PATCH'){assert.equal(b.force,false);const prev=this.refs.get('main');if(!this.ancestor(prev,b.sha))return response({},422);this.refs.set('main',b.sha);if(this.lostAck){this.lostAck=false;throw new TypeError('network after reference committed');}return response({object:{sha:b.sha}});}
    if(p.startsWith('/contents/')){const path=decodeURIComponent(p.slice(10)),head=u.searchParams.get('ref')||this.refs.get('main');const tree=this.trees.get(this.commits.get(head)?.tree.sha);const sha=tree?.[path];return sha?response({sha,encoding:'base64',content:Buffer.from(this.blobs.get(sha)).toString('base64')}):response({},404);}
    if(p==='/commits'){let cursor=this.refs.get('main'),out=[];while(cursor){const c=this.commits.get(cursor);out.push({sha:cursor,commit:{message:c.message}});cursor=c.parents[0];}return response(out);}
    if(p.startsWith('/compare/')){const [a,b]=p.slice(9).split('...');return response({status:a===b?'identical':this.ancestor(a,b)?'ahead':this.ancestor(b,a)?'behind':'diverged'});}
    throw Error('Unexpected route '+m+' '+p);
  }
}
async function fixture(){const repo=await new Repository().init(),storage=new Storage(),env={GITHUB_UPLOAD_TOKEN:'fixture-server-token',SOIL_ADMIN_PASSWORD:'246802',SESSION_SECRET:'fixture-only-long-session-secret-00000000000',WRITES_ENABLED:'true',ALLOWED_ORIGINS:ORIGIN};let now=Date.now();const service=new Service(env,storage,{fetcher:(...a)=>repo.fetch(...a),now:()=>now});let session='';
  const call=async(path,{method='GET',data,binary,headers={}}={})=>{const r=await service.handle(new Request(ENDPOINT+path,{method,headers:{Origin:ORIGIN,...(session?{Authorization:'Bearer '+session}:{}),...(data!==undefined?{'Content-Type':'application/json'}:{}),...(binary?{'Content-Type':'application/octet-stream'}:{}),...headers},body:data!==undefined?JSON.stringify(data):binary}));return {status:r.status,data:await r.json(),headers:r.headers};};
  const login=async(password=env.SOIL_ADMIN_PASSWORD)=>{const result=await call('/v1/login',{method:'POST',data:{password}});if(result.data.session)session=result.data.session;return result;};
  return {service,repo,storage,env,call,login,tick:n=>{now+=n;}};
}
function descriptor(key='soilType',bytes=enc.encode('binary fixture, not a production report')){const r=DIRECTORY.tasks[key].find(r=>r.city==='沧州市'&&r.district==='沧州市');return sha(bytes).then(hash=>({kind:'quality',files:[{name:`沧州市_市级_${TYPES[key]}_上传测试.pdf`,size:bytes.length,sha256:hash,batch:'2026年第二次第1批',associations:[{dataKey:key,city:r.city,unit:r.unit,district:r.district}]}]}));}
async function create(f,data,key='test-operation-unique-key-0001'){return f.call('/v1/uploads',{method:'POST',data,headers:{'Idempotency-Key':key}});}
function mainTree(repo){return repo.trees.get(repo.commits.get(repo.refs.get('main')).tree.sha);}

test('backend not configured fails closed and never returns credentials',async()=>{const f=await fixture();delete f.env.GITHUB_UPLOAD_TOKEN;const r=await f.login();assert.equal(r.status,503);assert.equal(r.data.code,'SERVICE_NOT_CONFIGURED');assert.ok(!JSON.stringify(r.data).includes('fixture'));assert.equal(f.repo.calls.length,0);});
test('administrator password is checked on server; no repository calls for wrong password',async()=>{const f=await fixture();const r=await f.login('111111');assert.equal(r.status,401);assert.equal(r.data.code,'ADMIN_PASSWORD');assert.equal(f.repo.calls.length,0);const no=await create(f,await descriptor());assert.equal(no.status,401);});
for(const password of ['246802',' 246802 ','２４６８０２','\u200b246802\ufeff'])test('password input normalization '+JSON.stringify(password),async()=>{const f=await fixture();assert.equal((await f.login(password)).status,200);});
test('login brute-force limit survives service instance replacement',async()=>{const f=await fixture();for(let i=0;i<10;i++)assert.equal((await f.login('bad')).status,401);assert.equal((await f.login()).status,429);f.tick(16*60000);assert.equal((await f.login()).status,200);});
test('expired, missing and forged sessions rejected; logout revokes',async()=>{const f=await fixture();assert.equal((await f.call('/v1/readiness')).status,401);await f.login();assert.equal((await f.call('/v1/readiness')).status,200);f.tick(31*60000);assert.equal((await f.call('/v1/readiness')).data.code,'SESSION_EXPIRED');await f.login();await f.call('/v1/logout',{method:'POST'});assert.equal((await f.call('/v1/readiness')).status,401);});
test('CORS and source validation, not wildcard and not sole authorization',async()=>{const f=await fixture();const r=await f.call('/v1/login',{method:'POST',data:{password:f.env.SOIL_ADMIN_PASSWORD},headers:{Origin:'https://attacker.test'}});assert.equal(r.status,403);assert.equal(r.headers.get('access-control-allow-origin'),null);const pre=await f.service.handle(new Request(ENDPOINT+'/v1/uploads',{method:'OPTIONS',headers:{Origin:ORIGIN}}));assert.equal(pre.status,204);assert.equal(pre.headers.get('access-control-allow-origin'),ORIGIN);});
test('read-only safety switch blocks all mutations',async()=>{const f=await fixture();f.env.WRITES_ENABLED='false';await f.login();assert.equal((await create(f,await descriptor())).data.code,'READ_ONLY');assert.equal((await f.call('/v1/delete-plans',{method:'POST',data:{paths:[QUALITY_ROOT+'/sample.pdf']}})).data.code,'READ_ONLY');});
for(const [failure,expected] of [[{status:401},'GITHUB_CREDENTIAL'],[{status:403},'GITHUB_PERMISSION'],[{status:403,headers:{'x-ratelimit-remaining':'0'}},'GITHUB_RATE_LIMIT'],[{status:429},'GITHUB_RATE_LIMIT'],[{status:503},'GITHUB_UNAVAILABLE'],[{throw:new TypeError('Failed to fetch')},'GITHUB_NETWORK'],[{throw:new DOMException('timeout','AbortError')},'GITHUB_TIMEOUT']])test('upstream failure classified '+expected,async()=>{const f=await fixture();await f.login();f.repo.failure=failure;const r=await f.call('/v1/readiness');assert.equal(r.data.code,expected);assert.notEqual(r.status,401);assert.ok(!JSON.stringify(r.data).includes('fixture-server-token'));assert.equal((await f.call('/v1/readiness')).status,200);});
test('8 result types resolve Cangzhou city using correct per-result directory',async()=>{for(const key of Object.keys(TYPES)){const d=descriptors(await descriptor(key)),row=d.files[0].associations[0];assert.equal(row.unit,key==='soilType'?'沧州华江工程勘察设计有限公司':'河北平普数政科技有限公司');assert.equal(row.directoryStatus,'matched');}});
test('all original and recovered merged task assignments checked without mutation',()=>{const before=JSON.stringify(DIRECTORY);let n=0;for(const key of Object.keys(TYPES))for(const r of DIRECTORY.tasks[key]){const a=assignment({dataKey:key,city:r.city,unit:r.unit,district:r.district});assert.equal(a.directoryStatus,'matched');n++;}assert.equal(JSON.stringify(DIRECTORY),before);assert.equal(n,1364);});
test('merged district and out-of-directory warnings preserve required meaning',()=>{const a=assignment({dataKey:'soilType',city:'邯郸市',district:'峰峰矿区',unit:'河北向力规划设计有限公司'});assert.equal(a.directoryStatus,'matched');assert.ok(a.directoryMessage.includes('单独质控'));const b={dataKey:'specialty',city:'邯郸市',district:'永年区',unit:'河北省农林科学院农业资源环境研究所'};assert.throws(()=>assignment(b),e=>e.code==='OUTSIDE_ACK_REQUIRED');const c=assignment({...b,unlistedConfirmed:true});assert.equal(c.directoryStatus,'outside-list');assert.ok(c.directoryMessage.includes('与作业单位通讯录不一致'));assert.ok(!c.directoryMessage.includes('不计入'));});
test('exact reviewed typo corrected; another result company is not overwritten',()=>{const a={dataKey:'soilType',city:'沧州市',district:'任丘市',unit:'河北图宇地理信息科技有限公司'};assert.equal(assignment(a).unit,'河北图宇科技有限公司');assert.equal(assignment({...a,dataKey:'soilAttr'}).directoryStatus,'unit-mismatch');});
test('28 registered shared reports retain only three approved categories and hashes',async()=>{assert.equal(DIRECTORY.registered.length,28);for(const r of DIRECTORY.registered){assert.deepEqual(r.keys,['soilType','soilAttr','farmland']);const f={name:r.name,size:r.size,sha256:r.sha256,batch:'2026年第一次第1批',associations:r.keys.flatMap(k=>r.byKey[k].map(a=>({dataKey:k,city:a.city,unit:a.unit,district:a.district})))};assert.equal(descriptors({kind:'quality',files:[f]}).files.length,1);assert.throws(()=>descriptors({kind:'quality',files:[{...f,sha256:'0'.repeat(64)}]}),e=>e.code==='REGISTERED_FILE_CHANGED');}});
test('invalid paths, types and privileged manifest fields denied',async()=>{for(const p of ['index.html','upload-config.js','data/admin-import-index.json','data/质控意见反馈_2026年第一批/a.pdf',QUALITY_ROOT+'/../a.pdf',QUALITY_ROOT+'/%2e%2e/a.pdf',REFERENCE_ROOT+'/attack.html','.github/workflows/x.yml'])assert.throws(()=>deletePath(p));const d=await descriptor();assert.throws(()=>descriptors({...d,targetBranch:'evil'}));assert.throws(()=>descriptors({...d,files:[{...d.files[0],size:96*1024*1024}]}));});
test('idempotent request preserves original operation; changed descriptor rejected',async()=>{const f=await fixture();await f.login();const d=await descriptor(),a=await create(f,d),b=await create(f,d);assert.equal(a.status,201);assert.equal(a.data.uploadId,b.data.uploadId);d.files[0].name='changed.pdf';assert.equal((await create(f,d)).data.code,'IDEMPOTENCY_CONFLICT');});
test('quality upload reaches original staging schema, with lost-ack and retry protection',async()=>{const f=await fixture();await f.login();const bytes=enc.encode('fixture-quality-report'),d=await descriptor('soilType',bytes),created=await create(f,d),id=created.data.uploadId;assert.equal((await f.call('/v1/uploads/'+id+'/finalize',{method:'POST'})).data.code,'PARTS_INCOMPLETE');const route=`/v1/uploads/${id}/files/0/parts/0`;assert.equal((await f.call(route,{method:'PUT',binary:bytes})).status,200);assert.equal((await f.call(route,{method:'PUT',binary:bytes})).data.reused,true);f.repo.lostAck=true;assert.equal((await f.call('/v1/uploads/'+id+'/finalize',{method:'POST'})).data.state,'archiving');await f.call('/v1/uploads/'+id+'/finalize',{method:'POST'});assert.equal(f.repo.calls.filter(c=>c.p==='/git/refs'&&c.m==='POST').length,1);const op=await f.service.requireOp(id),staged=f.repo.trees.get(f.repo.commits.get(f.repo.refs.get(op.branch)).tree.sha),m=JSON.parse(dec.decode(f.repo.blobs.get(staged['.soil-upload/'+id+'/manifest.json'])));assert.equal(m.targetBranch,'main');assert.equal(m.files[0].quality.associationsByDataKey.soilType[0].district,'沧州市');assert.equal(m.files[0].expectedSha256,await sha(bytes));assert.equal(m.chunkSize,39*1024*1024);assert.equal((await f.call('/v1/uploads/'+id)).data.state,'archiving');const head=f.repo.refs.get('main');f.repo.refs.set('main',await f.repo.addCommit(f.repo.commits.get(head).tree.sha,[head],'docs: import staged files '+id));assert.equal((await f.call('/v1/uploads/'+id)).data.state,'complete');});
test('chunked transport retains full 95 MiB acceptance and immutable uploaded chunks',async()=>{const f=await fixture();await f.login();const bytes=new Uint8Array(CHUNK+19);bytes[0]=1;bytes[CHUNK]=2;const d=await descriptor('soilType',bytes),c=await create(f,d),id=c.data.uploadId;for(let i=0;i<2;i++)assert.equal((await f.call(`/v1/uploads/${id}/files/0/parts/${i}`,{method:'PUT',binary:bytes.slice(i*CHUNK,(i+1)*CHUNK)})).status,200);assert.equal((await f.call(`/v1/uploads/${id}/files/0/parts/1`,{method:'PUT',binary:new Uint8Array(19)})).data.code,'CHUNK_CHANGED');const op=await f.service.requireOp(id),m=manifest(op);assert.equal(m.files[0].storage,'chunked');assert.equal(m.files[0].chunks.reduce((n,c)=>n+c.size,0),bytes.length);const big=structuredClone(d);big.files[0].size=95*1024*1024;assert.equal(descriptors(big).files[0].partCount,12);});
test('reference upload isolated to original reference root and workflow',async()=>{const f=await fixture();await f.login();const bytes=enc.encode('reference fixture'),d={kind:'reference',files:[{name:'模板测试.pdf',size:bytes.length,sha256:await sha(bytes),directory:REFERENCE_ROOT+'/总体报告'}]},c=await create(f,d),id=c.data.uploadId;await f.call(`/v1/uploads/${id}/files/0/parts/0`,{method:'PUT',binary:bytes});await f.call('/v1/uploads/'+id+'/finalize',{method:'POST'});const op=await f.service.requireOp(id);assert.ok(op.branch.startsWith('reference-upload-'));const m=manifest(op);assert.equal(m.kind,'reference');assert.equal(m.files[0].quality,undefined);assert.ok(!m.files[0].targetPath.startsWith('data/'));});
test('deletion is planned, confirmed and atomic with index cleanup; original rows survive',async()=>{const f=await fixture();const a=QUALITY_ROOT+'/a.pdf',b=REFERENCE_ROOT+'/b.pdf',keep=QUALITY_ROOT+'/keep.pdf';await f.repo.seed({[a]:enc.encode('a'),[b]:enc.encode('b'),[keep]:enc.encode('keep')},[{path:a,dataKey:'soilType'},{path:a,dataKey:'soilAttr'},{path:keep,dataKey:'farmland'}]);await f.login();const p=await f.call('/v1/delete-plans',{method:'POST',data:{paths:[a,b]}});assert.equal(p.data.associationsToRemove,2);const id=p.data.planId;assert.equal((await f.call('/v1/delete-plans/'+id+'/confirm',{method:'POST',data:{confirmed:false}})).status,400);const result=await f.call('/v1/delete-plans/'+id+'/confirm',{method:'POST',data:{confirmed:true}});assert.equal(result.status,200);const tree=mainTree(f.repo);assert.ok(!tree[a]&&!tree[b]&&tree[keep]);const index=JSON.parse(dec.decode(f.repo.blobs.get(tree[INDEX_PATH])));assert.deepEqual(index,[{path:keep,dataKey:'farmland'}]);const again=await f.call('/v1/delete-plans/'+id+'/confirm',{method:'POST',data:{confirmed:true}});assert.equal(again.data.commit,result.data.commit);assert.equal(f.repo.calls.filter(c=>c.m==='PATCH').length,1);});
test('concurrent changes after deletion preview reject stale confirmation',async()=>{const f=await fixture(),p=QUALITY_ROOT+'/report.pdf';await f.repo.seed({[p]:enc.encode('original')},[]);await f.login();const plan=await f.call('/v1/delete-plans',{method:'POST',data:{paths:[p]}});await f.repo.seed({[p]:enc.encode('new version')});const r=await f.call('/v1/delete-plans/'+plan.data.planId+'/confirm',{method:'POST',data:{confirmed:true}});assert.equal(r.data.code,'STALE_DELETE_PLAN');assert.equal(dec.decode(f.repo.blobs.get(mainTree(f.repo)[p])),'new version');});
test('lost deletion acknowledgement reconciled; never silently repeated',async()=>{const f=await fixture(),p='replies/test.pdf';await f.repo.seed({[p]:enc.encode('reply')},[]);await f.login();const plan=await f.call('/v1/delete-plans',{method:'POST',data:{paths:[p]}}),url='/v1/delete-plans/'+plan.data.planId+'/confirm';f.repo.lostAck=true;assert.equal((await f.call(url,{method:'POST',data:{confirmed:true}})).data.code,'GITHUB_NETWORK');assert.equal((await f.call(url,{method:'POST',data:{confirmed:true}})).status,200);assert.equal(f.repo.calls.filter(c=>c.m==='PATCH').length,1);});
test('standalone browser client exercises password→transfer→query, never transmits GitHub token',async()=>{const f=await fixture(),outgoing=[];const fetcher=async(url,options)=>{outgoing.push({url,headers:options.headers});return f.service.handle(new Request(url,{...options,headers:{...options.headers,Origin:ORIGIN}}));};const client=new ManagedUploadClient(ENDPOINT,{fetcher});await client.login(f.env.SOIL_ADMIN_PASSWORD);const bytes=enc.encode('client binary fixture'),d=await descriptor('reports',bytes),op=await client.create(d,'browser-request-00000001');const result=await client.transfer(op,[new Blob([bytes])]);assert.equal(result.state,'archiving');assert.equal((await client.status(op.uploadId)).state,'archiving');assert.ok(outgoing.every(r=>r.url.startsWith(ENDPOINT)));assert.ok(!JSON.stringify(outgoing).includes(f.env.GITHUB_UPLOAD_TOKEN));});
test('browser connectivity errors are not mislabeled as password errors',async()=>{const client=new ManagedUploadClient(ENDPOINT,{fetcher:()=>Promise.reject(new TypeError('Failed to fetch'))});await assert.rejects(()=>client.login('unused'),e=>e.code==='BROWSER_NETWORK'&&!e.message.includes('密码错误'));});

// Machine-readable evidence (tests use isolated Git doubles, never production).
test('write bounded test summary',()=>{fs.mkdirSync(new URL('../test-results/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../test-results/scope.json',import.meta.url),JSON.stringify({mode:'isolated backend and client; GitHub responses mocked; no production writes',directoryTasks:1364,registeredReports:28,originalDirectoryHashes:DIRECTORY.hashes,managedModules:Object.keys(TYPES).concat('reference','managed-delete'),notConnected:['active frontend','public reply upload','public work-record creation','production Cloudflare deployment']},null,2));});
