'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const B=require('../quality-batches.js');
const C=require('../work-records-core.js');
assert.strictEqual(B.label('第一批'),'2026年第一次第1批');
assert.strictEqual(B.label('第二批补充'),'2026年第一次第2批（补充）');
assert.strictEqual(B.label('第三批'),'2026年第一次第3批');
assert.strictEqual(B.label('第一轮'),'2026年第一次第1批');
assert.strictEqual(B.key('第一轮'),B.key('2026年第一次第1批'));
assert.notStrictEqual(B.key('2026年第一次第1批'),B.key('2026年第二次第1批'));
assert.notStrictEqual(B.key('2026年第一次第2批'),B.key('第二批补充'));
assert.strictEqual(B.fromText('2026年第二次质控/第三批/平山县土壤属性图.pdf'),'2026年第二次第3批');
assert.strictEqual(B.choose('第一轮','安国市第三次全国土壤普查成果质控报告.docx'),'2026年第一次第1批','不能把第三次全国土壤普查当作第三次质控');
assert.strictEqual(B.choose('第一批','2027年第二次质控_第一批.pdf'),'2027年第二次第1批');
assert.strictEqual(B.choose('第一轮','文件.pdf',{year:2026,round:2,batch:2,supplement:true}),'2026年第二次第2批（补充）');
assert.strictEqual(B.unique(['第一批','第一轮','2026年第一次第1批','2026年第二次第1批']).length,2);
const ctx={window:{SoilQualityBatches:B}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('reply-workflow-core.js','utf8'),ctx);
const R=ctx.window.SoilReplyWorkflow;
const old='城市_单位_区县_批次-第一批_整改答复_20260901010101.pdf';
const key=R.replyKey('城市','单位','区县','2026年第一次第1批');
assert(R.buildIndex([old])[key]);
assert(!R.buildIndex([old])[R.replyKey('城市','单位','区县','2026年第二次第1批')]);
assert.strictEqual(R.buildIndex([old,'城市_单位_区县_批次-2026年第一次第1批_整改答复_20260902010101.pdf'])[key].time,'20260902010101');
const r=C.normalize({id:'wr-12345678',title:'会议 A',time:'2026-09-19T09:00',location:'保定',people:'测试人员',notes:'类型图反馈',attachments:[]});
assert(C.validate(r));assert(C.matches(r,'会议 保定'));assert(!C.matches(r,'会议 唐山'));
assert(!C.matches(r,'','2026-10-01',''));assert(C.matches(r,'','','2026-09-19'));
assert(C.isImage('样例.JPG'));assert(!C.isImage('script.svg'));
assert.throws(()=>C.validateFile({name:'file.html',size:20}));
assert.throws(()=>C.validateFile({name:'file.pdf',size:96*1024*1024}));
assert(C.validateFile({name:'file.docx',size:200}));
assert.throws(()=>C.validate(C.normalize({...r,title:''})));
assert.throws(()=>C.validate(C.normalize({...r,time:'2026-02-31T09:00'})));
assert.strictEqual(C.esc('<img src=x onerror=alert(1)>').includes('<img'),false);
const loader=fs.readFileSync('page-enhancements.js','utf8'),version=fs.readFileSync('VERSION','utf8').trim().slice(1);
for(const name of ['work-records-core.js','work-records-store.js','work-records-gallery.js','work-records.js','quality-batch-controls.js'])assert(loader.includes(name+'?v='+version),name+'未按版本加载');
const store=fs.readFileSync('work-records-store.js','utf8'),work=fs.readFileSync('work-records.js','utf8');
assert(!/SoilAdminAutoClassifier|SoilReferenceUpload|\.state\.files|new MutationObserver|window\.fetch\s*=/.test(store),'独立工作记录不得进入其他模块状态或替换fetch');
assert(work.includes('requestAdmin'));assert(store.includes('indexedDB.open'));assert(store.includes('tx.oncomplete'));
assert(store.includes('baseRevision'));assert(store.includes('C.validateFile(item.file)'), '附件必须使用统一的大小和扩展名校验');
assert(work.includes('aria-label="查询工作记录"'));assert(work.includes('表格展示'));
const gallery=fs.readFileSync('work-records-gallery.js','utf8');assert(gallery.includes('Numpad8'));assert(gallery.includes('wheel'));assert(gallery.includes('translate3d'));assert(gallery.includes('prefers-reduced-motion'));
assert(fs.readFileSync('work-records.css','utf8').includes('object-fit:contain'));
const registry=JSON.parse(fs.readFileSync('data/work-records/index.json','utf8'));assert.strictEqual(registry.schemaVersion,1);
console.log('v1.2.0: batch aliases/round isolation/legacy replies/work record validation/search/attachments passed');
