name = "soil-type-mapping-upload"
main = "src/index.js"
compatibility_date = "2026-07-25"
workers_dev = true

[vars]
GITHUB_REPOSITORY = "1337816143/soil-type-mapping-inventory"
GITHUB_BRANCH = "main"
ALLOWED_ORIGINS = "https://1337816143.github.io"
MAX_FILE_MB = "20"
